# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json
name: aks-hf-xet
metadata:
  template: aks-hf-xet@0.0.1-beta

infra:
  provider: bicep
  path: ./infra

# Docker build/push and K8s deployment handled by deploy.ps1 script
# Run: ./scripts/deploy.ps1

hooks:
  postprovision:
    windows:
      shell: pwsh
      run: ./scripts/deploy.ps1
      interactive: true
      continueOnError: false
    posix:
      shell: sh
      run: ./scripts/deploy.sh
      interactive: true
      continueOnError: false

pipeline:
  provider: github
